from aiogram.types import KeyboardButton

represent_btn = KeyboardButton('Показать данные 📊')
settings_btn = KeyboardButton('Настройки ⚙')
main_menu_btn = KeyboardButton('Главное меню 📅')
first_view_btn = KeyboardButton('📈 По месяцам')
second_view_btn = KeyboardButton('📉 За год')
info_btn = KeyboardButton('🎉 Выходные')
edit_holidays_btn = KeyboardButton('✏️ Редактировать\nвыходные')
reset_holidays_btn = KeyboardButton('🗑 Сбросить\nвыходные')
go_back_btn = KeyboardButton('Назад ↩️')
edit_holidays_save_btn = KeyboardButton('💾 Сохранить')
edit_holidays_cancel_btn = KeyboardButton('⛔️ Отмена')
yes_btn = KeyboardButton('Да 💢')
no_btn = KeyboardButton('Нет ❎')
